# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88df55f22701817c402a5b980aacd48d6b5810345c3aa366b3cc771167b61665acc90c551c66902002347afbb2a72339d4a781fe1a8a263e82b48535c66345f

test:
  secret_key_base: 41c13e3d110bb79337ea7ed31525b2a7f02a2791deb452ada4e040b1a8328d34f4adf7ed2dc0d01019d0e574987190f8a2704d10002ad8b4abc1b58cc1a1a94d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
